// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAP4IeLaOO6d2VGOEq4ivioGRRWl-I014',
    appId: '1:116204902612:web:aecaeaf38ef8e4b1864341',
    messagingSenderId: '116204902612',
    projectId: 'steamapp-77c4e',
    authDomain: 'steamapp-77c4e.firebaseapp.com',
    storageBucket: 'steamapp-77c4e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp0nrj5X5mtfGcu_v6g6CsgFuU2IFub7U',
    appId: '1:116204902612:android:c543615a61dba2e4864341',
    messagingSenderId: '116204902612',
    projectId: 'steamapp-77c4e',
    storageBucket: 'steamapp-77c4e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWFLpV5mmoexCP-b2giF5UkF1ok8fQlY4',
    appId: '1:116204902612:ios:6cec694fa5ef1454864341',
    messagingSenderId: '116204902612',
    projectId: 'steamapp-77c4e',
    storageBucket: 'steamapp-77c4e.appspot.com',
    iosClientId: '116204902612-m1f9tn10h1l577fahksr9cdcpmc2q7gp.apps.googleusercontent.com',
    iosBundleId: 'com.example.steamProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWFLpV5mmoexCP-b2giF5UkF1ok8fQlY4',
    appId: '1:116204902612:ios:6cec694fa5ef1454864341',
    messagingSenderId: '116204902612',
    projectId: 'steamapp-77c4e',
    storageBucket: 'steamapp-77c4e.appspot.com',
    iosClientId: '116204902612-m1f9tn10h1l577fahksr9cdcpmc2q7gp.apps.googleusercontent.com',
    iosBundleId: 'com.example.steamProject',
  );
}
